export const LECTURE_AND_EXERCISES = 'LECTURE_AND_EXERCISES';
export const OTHER = 'OTHER';
export const SEMINAR = 'SEMINAR';
export const COURSE = 'COURSE';
export const COLLOQUIUM = 'COLLOQUIUM';
export const EXAM = 'EXAM';
export const REPETITION_EXAM = 'REPETITION_EXAM';
export const PROSEMINAR = 'PROSEMINAR';
export const EXERCISES = 'EXERCISES';
export const TUTORIAL = 'TUTORIAL';
export const PRACTICAL_TRAINING = 'PRACTICAL_TRAINING';
export const FIELD_TRIP = 'FIELD_TRIP';
export const INDEPENDENT_STUDY = 'INDEPENDENT_STUDY';
export const WORK = 'WORK';
export const LANGUAGE_COURSE = 'LANGUAGE_COURSE';
export const MEETING = 'MEETING';
export const INTRODUCTION = 'INTRODUCTION';
export const REVISION = 'REVISION';

export type ModuleType =
	| 'LECTURE_AND_EXERCISES'
	| 'OTHER'
	| 'SEMINAR'
	| 'COURSE'
	| 'COLLOQUIUM'
	| 'EXAM'
	| 'REPETITION_EXAM'
	| 'PROSEMINAR'
	| 'EXERCISES'
	| 'TUTORIAL'
	| 'PRACTICAL_TRAINING'
	| 'FIELD_TRIP'
	| 'INDEPENDENT_STUDY'
	| 'WORK'
	| 'LANGUAGE_COURSE'
	| 'MEETING'
	| 'INTRODUCTION'
	| 'REVISION';
